kind: Service
apiversion: v1
metadata: 
   name: kubernetes
   labels: 
     apps: kubernetes
spec: 
  ports: 
    - port: 8080
      targetport: 80
      nodeport: 31200
  selector:
    app: kubernetes
  type: LoadBalancer  


